name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 'npm install' will be executed with 'jest-action'
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4

      - name: if fail # This is one of step
        uses: actions/github-script@0.2.0  # github-script 액션을 사용한다.
        with:
          github-token: ${{github.token}}  # github token을 선언해준다
          script: |                        # script에 원하는 스크립트를 작성
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body:"테스트코드를 다시 확인해주세요. ",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number,
              state: "closed"
            })
        if: failure() # Execute only last step is fail
